version: '4'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nss_crm
    volumes:
      - ./data:/var/lib/postgresql/data

  usermanagement-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: usermanagement-2
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/nss_crm?currentSchema:usermanagement
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: Rn0xiEBzpGU6NnN7ejndJBIQbjzRHO7697zqQTm6cW22tcQCNjq5tINinpa16rb8b3ZRZYdxJ5fKVblcAJS/Dw==
      JWT_EXPIRATION: 3600000
      JWT_REFRESH_EXPIRATION: 86400000
    depends_on:
      - postgres

volumes:
  postgres-data:
